### PR TITLE
Improve CI

### PR DESCRIPTION
**Pull request by juancarlospaco**
- Fix style to allow using ` --stylecheck:error `.
- Improve CI using a combined matrix:

```yaml
matrix:
  os:             [ubuntu-latest, windows-latest, macos-latest]
  architecture:   [x64, x86]
  nim-channel:    [stable, devel]
  python-version: ["3.5", "3.6", "3.7"]  

```

When https://github.com/yglukhov/nimpy/issues/249 is fixed, `"2.7", "3.8", "3.9", "3.10"` can be added to the CI (add them to the YAML to reproduce the bug).

### CODE REVIEW

**Comment by yglukhov** [comment]
@juancarlospaco whats the state of this? The conflict state has been there since PR creation.

**Comment by juancarlospaco** [comment]
@yglukhov
The PR is ready, it is an improvement over the current one whatsoever.

I dont know why Nimpy does not work with Python "2.7", "3.8", "3.9", "3.10",
all I know is in the bug report https://github.com/yglukhov/nimpy/issues/249#issue-1090278058
🙂

**Comment by yglukhov** [comment]
Ok, but please fix the conflicts :)

**Comment by juancarlospaco** [comment]
The Github UI and the diff and the local do not show merge conflicts for me...

**Comment by yglukhov** [comment]
My bad, thank do do i was only in rebase mode

**Comment by juancarlospaco** [comment]
Thanks, sorry about the confusion, I am just trying to help...
🙂

**Comment by yglukhov** [comment]
@juancarlospaco I just took another look at this, and don't understand why is there `architecture` axis? It is not used anywhere.

**Comment by juancarlospaco** [comment]
@yglukhov You are right,  ...but by the magic of GitHub it still works, observe:

**Comment by yglukhov** [comment]
I don't deny there's twice as much jobs. I imply they are doing the same thing, and thus are redundant, aren't they?

**Comment by juancarlospaco** [comment]
It is running CI on 32 Bits. 🙂

**Comment by juancarlospaco** [comment]
If you think is too much feel free to Disable the 32 Bit, I dunno. 🤷

**Comment by juancarlospaco** [comment]
@yglukhov You are right, it should be removed. 🙁

**Pull request merged**
