### PR TITLE
Make pyexport work on Nim executables.

### PR DESCRIPTION
**Pull request by chrisheller**
Works on Python2/Python3.

Updated test cases included.

Part of #139

### CODE REVIEW

**Comment by yglukhov** [comment]
Very cool! Thanks!

**Comment by yglukhov** [comment]
Oh no! `nimble test` failed on my arch! :)
```
...
Hint: 56070 LOC; 1.066 sec; 73.457MiB peakmem; Debug build; proj: ~/nimpy/tests/tbuiltinpyfromnim.nim; out: ~/nimpy/tests/tbuiltinpyfromnim [SuccessX]
Hint: ~/nimpy/tests/tbuiltinpyfromnim  [Exec]
~/nimpy/tests/tbuiltinpyfromnim.nim(10) tbuiltinpyfromnim
~/nimpy/nimpy.nim(1273) pyImport
~/nimpy/nimpy/py_lib.nim(495) initPyLibIfNeeded
~/nimpy/nimpy/py_lib.nim(457) initPyThreadFrame
~/nimpy/nimpy/py_lib.nim(429) initPyLib
~/nimpy/nimpy/py_lib.nim(418) loadModulesFromThisProcess
Error: unhandled exception: Init symbol not found for module: other_module [Exception]
Error: execution of an external program failed: '~/nimpy/tests/tbuiltinpyfromnim '
stack trace: (most recent call last)
/tmp/nimblecache/nimscriptapi.nim(165, 16)
~/nimpy/nimpy_57736.nims(42, 11) testTask
~/nimpy/nimpy_57736.nims(39, 12) runTests
~/nim-new/lib/system/nimscript.nim(260, 7) exec
~/nim-new/lib/system/nimscript.nim(260, 7) Error: unhandled exception: FAILED: nim c -r  tests/tbuiltinpyfromnim.nim [OSError]
     Error: Exception raised during nimble script execution
```

**Comment by chrisheller** [comment]
I just reproduced this.  Seems to not be finding the symbols for the init proc in the compiled binary.  nm shows that they are there though.   

I was using symAddr to get the init function address because I didn't see an easy way to get the addresses directly from the py2init and py3init procs that get setup in the declarePyModuleIfNeededAux template.  If I could get those addresses directly, they could be stored in a lookup table like the module names are.

**Comment by chrisheller** [comment]
By taking out the dynlib pragma in the py2init and py3init,  you can actually extract the proc addresses by parsing the .repr() output for them.  Saving the addresses off so that they can be given to PyImport_AppendInittab then works properly and passes all tests,  but it is not a good way to solve this.  

I'm not sure why symAddr is not returning the addresses on Linux when compiled as an executable though.

**Pull request merged**
