### PR TITLE
Some fixes for python9

### PR DESCRIPTION
**Pull request by yglukhov**

### CODE REVIEW

**Comment by carver** [comment]
Thanks for the quick action! I'm now getting:
```
~/.nimble/pkgs/nimpy-0.1.1/nimpy/py_types.nim(74, 68) Error: undeclared identifier: 'csize_t'
```
which looks like it was added here.

**Comment by narimiran** [comment]
> `Error: undeclared identifier: 'csize_t'`

This is because newer versions warn that `csize` is deprecated.

@yglukhov the usual fix for this is:

```nim
when (NimMajor, NimMinor) < (1, 2):
  type csize_t = csize
```

**Comment by yglukhov** [comment]
Fixed

**Comment by carver** [comment]
Thanks! Just linking for reference: b3a7f1a9bf12d847a263

**Pull request merged**
