### PR TITLE
Upload to PyPI using GitHub Actions

### PR DESCRIPTION
**Pull request by juancarlospaco**
- Upload to PyPI using GitHub Actions, Documentation only.

:slightly_smiling_face:

### CODE REVIEW

**Comment by yglukhov** [comment]
Thank you, but I'm on the fence about this one. Firstly it doesn't look like it handles cross-platform-ness properly, so it can't be used blindly as a cookbook recipe. But even then the info is pretty specific and shouldn't go into the main readme imo. How about adding it to the wiki instead, and add a FAQ entry "How do I publish a nimpy package to pypi" to the readme with the link to the wiki?

**Comment by juancarlospaco** [comment]
But PYPI has classifiers that let you specify on which OS the package targets.
https://pypi.org/classifiers :arrow_right: `Operating System :: POSIX :: Linux`.
Also it says is like a Template that you must edit to work correctly.

**Comment by juancarlospaco** [comment]
The Wiki is Disabled from the Settings of the Repo.
If I go to https://github.com/yglukhov/nimpy/wiki it redirects to https://github.com/yglukhov/nimpy
Try opening https://github.com/yglukhov/nimpy/wiki on an Incognito web browser tab.
:stuck_out_tongue:

**Comment by yglukhov** [comment]
I've added a home page, please try again.

**Comment by juancarlospaco** [comment]
Home page of Wiki works `Welcome to the nimpy wiki!`.
But is Read-Only for me, no Edit button, etc (Wikis of other projects work).
I think you need to go to https://github.com/yglukhov/nimpy/settings and check the Wiki settings there.

**Comment by yglukhov** [comment]
Right, sorry, should be good now.

**Comment by juancarlospaco** [comment]
This pull request is no more, so I am Closing it.

**Comment by juancarlospaco** [comment]
Yes, it works now :grey_exclamation: 
:slightly_smiling_face:

**Pull request closed without merging**
